### ISSUE TITLE
Building img_murphy.dll / img_murphy.so

### ISSUE THREAD

**Issue by askervin** [F-Secure/murphy#1]
Any plans on releasing sources for these libraries? It would help using Murphy with 64-bit Python.

**Comment by suarmagit** [comment]
yes, i've been quite busy with a newer version so it may take a while

**Comment by pombredanne** [comment]
I guess without the sources for these .so/.dll, there is not much that can be done.

**Comment by noxdafox** [comment]
Source code available in: https://github.com/F-Secure/murphy/blob/master/murphy/img_murphy.c
